import Masthead from "../components/Masthead";

export default function Home() {
  return (
    <>
      <Masthead />
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
      <p>rest of the page</p>
    </>
  );
}
